language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cxTyXbaszzOT88S6eHR1zwLMATTiMdeHuxgdriT7MVWj7ASpeDpVbINeKXwfOHUjkX7sXgjbAaGHhCIS8P6qjxWg/aYMrPzNWqYuCS92zY7VeaimosPXXOdhTi8iI352a5+MrZgMedebY7J+JAYVI9hsyN0ny9ZhE6/nE0BjU9AgbX6zG0foPmhQWwH48Cr2AlUXY4/B2w4eDvNChENkp+/J9jVv6cd/jOS4eGDToB+FN5dvZ1cZrDaVsW5nk/BU8+Q+OhNM99LZOUfK7UXhAgH7Cyskb6BA1UtQTv95Tf5BGPcznBb1EnNkqWWdwWi7TOuQZX37ehsD6bZExh+/wFWrcmOWvp2hKiLgioGn9HA90l9HIexHiGUg/Afm4VM1GAbgjFKVcEDe+vrLeHy8FJEHx6H2qhjID2F68SE/ekdSnmGZtJ+akniymc4lxkSeNwft/HJqxuT6e38Z372BF9G8TP73MiUt60uIPZLL9wwfgld94VBaLUnnzpPxHovSJ2MufyIbdi3UJUw91P1W2p3YDXA67HmxXAawgbBYAGVB0xLNmbl/V3RRyULevAWhgIJ8k07vO5X4Kbp7kNfGIiyq6aMbuo+4860o+gdH/iyEalFsIGzJ/deEVfpsOcca7tgJnERY6kJsEAyjXoiid/B5jzOxwv8yI8e0I2NLqFU=
  app: devops-pipeline-bona
  edge: true
